# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy-rag-import-function
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - prod-rag-import-function
      - --gen2
      - --region=${_REGION}
      - --source=cloud_function/
      - --runtime=python312
      - --entry-point=main
      - --build-service-account=${_BUILD_SA_ID}
      - --trigger-bucket=${_KNOWLEDGE_BUCKET}
      - --service-account=${_CF_SA_EMAIL}
      - --set-env-vars=RAG_CORPUS_NAME=${_RAG_CORPUS_NAME}
      - --timeout=180s
      - --max-instances=3
      - --memory=512MB
      - --trigger-location=${_REGION}
      - --retry
      - --ingress-settings=internal-only

  - name: "python:3.11-slim" 
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv==0.6.12 --user && uv sync --frozen
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  - name: "python:3.11-slim"
    id: trigger-deployment
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        uv export --no-hashes --no-sources --no-header --no-dev --no-emit-project --no-annotate --frozen > .requirements.txt
        uv run app/agent_engine_app.py \
          --project ${_PROD_PROJECT_ID} \
          --location ${_REGION} \
          --set-env-vars="COMMIT_SHA=${COMMIT_SHA}"
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: us-central1
  _RAG_CORPUS_NAME: YOUR_RAG_CORPUS_NAME
  _BUILD_SA_ID: YOUR_BUILD_SA_ID
  _CF_SA_EMAIL: YOUR_CF_SA_EMAIL
  _KNOWLEDGE_BUCKET: YOUR_KNOWLEDGE_BUCKET

logsBucket: gs://${PROJECT_ID}-study-helper-agent-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
