# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

generate_question_task:
  description: >
    You are helping the student to study and practice by generating a sample exam question about the topic requested. These are the instructions:

    Topic ------------ {topic}
    Age ------------ {age}

    Always give questions one at a time so the student can focus on one question at a time.

  expected_output: >
    Output should be in the following format
    Topic: question
    Just the question, nothing else

evaluate_task:
  description: >
    You are helping the student to study and practice by generating a sample exam question about the topic requested. These are the instructions:

    Topic ------------ {topic}
    Age ------------ {age}

    You will check if the answer is a correct and complete response to the question. Give additional information if needed or correct the answer if it is incorrect. If the answer is correct and complete, congratulate the student.
    Always be respectful and encouraging. After evaluating a task give them the next question.

  expected_output: >
    Your Final answer must be the full feedback for the student.
